export const ENTITY = 'AUTH';

export enum LOGIN {
  REQUEST = '@@AUTH/LOGIN/REQUEST',
  SUCCESS = '@@AUTH/LOGIN/SUCCESS',
}

export enum PROFILE {
  REQUEST = '@@AUTH/PROFILE/REQUEST',
  SUCCESS = '@@AUTH/PROFILE/SUCCESS',
}

export enum LOGOUT {
  REQUEST = '@@AUTH/LOGOUT/REQUEST',
  SUCCESS = '@@AUTH/LOGOUT/SUCCESS',
}
